export const STELLAR_NETWORK = process.env.NEXT_PUBLIC_STELLAR_NETWORK || "TESTNET";
export const STELLAR_RPC_URL = process.env.NEXT_PUBLIC_STELLAR_RPC_URL || "https://soroban-testnet.stellar.org";
export const NETWORK_PASSPHRASE = process.env.NEXT_PUBLIC_NETWORK_PASSPHRASE || "Test SDF Network ; September 2015";

export const CONTRACT_EMPLOYEE_REGISTRY = process.env.NEXT_PUBLIC_EMPLOYEE_REGISTRY_ID || "CAQDRPEBKLSP4LO5IU43MJLUNWEJFX2RE4ZLQ24TCBFZAZMRCZZM6XHI";
export const CONTRACT_TREASURY = process.env.NEXT_PUBLIC_TREASURY_ID || "CBM22RSREUH3PZCK4YU5IXIBO626VIXO72LLK2CCCCILOL5GKR5F2EVB";
export const CONTRACT_PAY_TOKEN = process.env.NEXT_PUBLIC_PAY_TOKEN_ID || "CD62ZXYYQPNZCZ32XL6NIOTFRD4SXAV5UZX7QX3KL7HWOLDTIRMSKVB2";
export const ISSUER_ADDRESS = process.env.NEXT_PUBLIC_ISSUER_ADDRESS || "GCBWYUW62CQBQ2JG3EU6AFIEA3KKHHM5C3R32LZTJCBXOZMLKL4WQGAN";

export const TOKEN_SYMBOL = "PAY";
export const STROOPS_PER_TOKEN = 10_000_000n; // 7 decimals standard in Stellar
export const SECONDS_PER_YEAR = 365 * 24 * 60 * 60; // 31,536,000 seconds
